using SmashUp.Backend.GameObjects;
using SmashUp.Backend.Models;
using SmashUp.Frontend.Pages.Battle.LogicModules;
using SmashUp.Frontend.Utilities;
using System.Text;

namespace SmashUp.Frontend.Pages.Battle
{
    /// <summary>
    /// Handles all rendering the Battle page
    /// </summary>
    internal class BattlePage(List<BaseSlot> baseSlots, Player activePlayer, BattlePageTargeter targeter) : ValuePage<Guid>
    {
        private readonly BattlePageTargeter _targeter = targeter;
        private readonly List<BaseSlot> _baseSlots = baseSlots;
        private readonly Player _activePlayer = activePlayer;

        //Eventually I want the InputField to be generated by generic blocks rather than hardcoded options
        //This way we can display anything we could want down there
        private readonly PlayableCard? _cardToDisplay;
        private readonly string _displayText = "";

        // STATIC VARIABLES
        readonly int CARD_FIELD_SIZE = 15;

        // Eventually I want a system where all selectable UI elements are generated with a Guid
        readonly Guid END_TURN_BUTTON_ID = Guid.NewGuid();

        protected override StringBuilder GenerateRender(int consoleWidth, int consoleHeight)
        {
            int baseFieldPadding = 1;
            int statFieldPadding = 1;
            int otherRenderGraphicsLength = 1;

            //Initalize vars and generate fields
            StringBuilder? renderBuffer = null;
            var debugField = GenerateDebugField();
            var baseField = GenerateBaseField(consoleWidth);
            var statField = GenerateStatField();
            var consoleField = GenerateInputField(new[] { baseField.Max(line => line.Length), statField.Max(line => line.Length) }.Max());
            var endTurnField = GenerateEndTurnField(baseField.Max(line => line.Length));

            //Ensure the current console size will fit the header
            int renderWidth = new[] {
                debugField.Length > 0 ? debugField.Max(line => line.Length) : 0,
                baseField.Max(line => line.Length),
                statField.Max(line => line.Length),
                consoleField.Length > 0 ? consoleField.Max(line => line.Length) : 0,
                endTurnField.Max(line => line.Length)
            }.Max();

            int renderHeight = debugField.Length +
                               baseField.Length +
                               baseFieldPadding +
                               statField.Length +
                               statFieldPadding +
                               consoleField.Length +
                               endTurnField.Length +
                               otherRenderGraphicsLength;

            //Make sure the whole render can fit in the console
            if (consoleHeight - 1 >= renderHeight && consoleWidth - 1 >= renderWidth)
            {
                //Generate final combined render
                string[] render = new string[renderHeight];
                int i = 0;
                foreach (string line in debugField)
                {
                    render[i++] = line;
                }
                foreach (string line in baseField)
                {
                    render[i++] = line;
                }
                i += baseFieldPadding;

                //Separation Graphic
                StringBuilder lineBuilder = new();
                lineBuilder.Append('─', renderWidth);
                render[i++] = lineBuilder.ToString();

                foreach (string line in statField)
                {
                    render[i++] = line;
                }
                i += statFieldPadding;
                foreach (string line in consoleField)
                {
                    render[i++] = line;
                }
                foreach (string line in endTurnField)
                {
                    render[i++] = line;
                }

                renderBuffer = RenderUtil.Center(render, (consoleHeight - 1, consoleWidth - 1));
            }
            //Let the user know the screen is too small
            if (renderBuffer is null)
            {
                string[] render =
                [
                    $@"Please increase your screen size"
                ];
                renderBuffer = RenderUtil.Center(render, (consoleHeight - 1, consoleWidth - 1));
            }

            return renderBuffer;
        }

        /// <summary>
        /// Debug stats
        /// </summary>
        /// <returns></returns>
        private string[] GenerateDebugField()
        {
            if (_targeter.IsInDebugMode() == true)
            {
                (var x_index, var y_index) = _targeter.GetDebugVals();

                return [$"(X: {x_index}, Y: {y_index})"];
            }
            return [];
        }

        /// <summary>
        /// Generates the base graphics
        /// </summary>
        private string[] GenerateBaseField(int consoleWidth)
        {
            List<BaseCard> activeBases = _baseSlots.Select(x => x.BaseCard).ToList();

            // Get Active Bases Graphics
            string[][] activeBasesGraphics = activeBases
                .Select(GenerateBaseGraphic)
                .ToArray();

            // Get Attached Cards Graphics
            string[][] attachedCardGraphics = _baseSlots
                .Select(GetBaseAttachmentGraphics)
                .ToArray();

            if (activeBasesGraphics.Length != attachedCardGraphics.Length) throw new Exception($"Recieved {activeBasesGraphics.Length} active bases but only {attachedCardGraphics.Length} attached card graphics. They should be equal");

            // Calculate array size
            int baseGraphicHeight = activeBasesGraphics.Max(baseGraphic => baseGraphic.Length);
            int paddingHeight = 1;
            int numCardFieldLines = Math.Max(attachedCardGraphics.Max(x => x.Length), CARD_FIELD_SIZE);
            var baseField = new string[baseGraphicHeight + paddingHeight + numCardFieldLines];

            // Calculate padding
            int baseGraphicWidth = activeBasesGraphics.Max(baseGraphic => baseGraphic.Max(line => line.Length));
            int horizontalPaddingLength = (consoleWidth - 1 - baseGraphicWidth * activeBases.Count) / (activeBases.Count + 1);

            // Generate combined graphics
            for (int i = 0; i < baseField.Length; i++)
            {
                StringBuilder lineBuilder = new();

                for (int j = 0; j < activeBases.Count; j++)
                {
                    if (i < activeBasesGraphics[j].Length)
                    {
                        lineBuilder.Append(activeBasesGraphics[j][i]);

                        if (j < activeBases.Count - 1 && horizontalPaddingLength > 0)
                            lineBuilder.Append(' ', horizontalPaddingLength);
                    }
                    else if (i < activeBasesGraphics[j].Length + paddingHeight)
                    {
                        lineBuilder.Append(string.Empty);
                    }
                    else
                    {
                        int attachedCardIndex = i - (baseGraphicHeight + paddingHeight);
                        int currBaseArea = activeBasesGraphics[j].Max(x => x.Length) + horizontalPaddingLength;

                        string currString = attachedCardIndex < attachedCardGraphics[j].Length
                            ? attachedCardGraphics[j][attachedCardIndex]
                            : string.Empty;

                        lineBuilder.Append(RenderUtil.LeftJustifyString(currString, currBaseArea));
                    }
                }

                baseField[i] = lineBuilder.ToString();
            }

            return baseField;
        }

        private string[] GetBaseAttachmentGraphics(BaseSlot baseSlot)
        {
            return CardGraphicUtil.GetAttachedCardsGraphic(baseSlot, _targeter.GetTargetId());
        }

        private string[] GenerateBaseGraphic(BaseCard baseCard)
        {
            bool isHighlighted = baseCard.Id == _targeter.GetTargetId();
            return CardGraphicUtil.GenerateBaseCardGraphic(baseCard.Graphic, baseCard.Name, baseCard.CurrentPower, baseCard.CurrentBreakpoint, isHighlighted);
        }

        /// <summary>
        /// Generates the field that lists the game statistics
        /// </summary>
        private string[] GenerateStatField()
        {
            //These are all the elements of the stat field
            List<string> statFieldElements =
            [
                $"{_activePlayer.Name}'s Turn",
                $"Minion Plays: {_activePlayer.MinionPlays}",
                $"Action Plays: {_activePlayer.ActionPlays}",
                $"VP: {_activePlayer.VictoryPoints}"
            ];

            //Join elements and padding
            string elementSeparator = $" | ";
            string paddedStatField = string.Join(elementSeparator, statFieldElements);

            //Return as array
            return [paddedStatField];
        }

        /// <summary>
        /// Generates the field that displays the result of user input. Usually will be their hand, but is also how they view their decks
        /// </summary>
        private string[] GenerateInputField(int fieldLength)
        {
            string[][] GraphicsToDisplay = [];

            if (_cardToDisplay != null)
            {
                GraphicsToDisplay = [GenerateDisplayCardGraphic()];
            }
            else
            {
                // Hand Display
                if (_activePlayer.Hand.Count > 0)
                {
                    string[][] allGraphics = _activePlayer.Hand.Select(GeneratePlayableCardGraphic).ToArray();

                    int cardLength = allGraphics.Max(graphic => graphic.Max(line => line.Length));
                    int numCardsToDisplay = Math.Min(fieldLength / (cardLength + 1), _activePlayer.Hand.Count);
                    GraphicsToDisplay = allGraphics[..numCardsToDisplay];
                }
            }

            int cardHeight = GraphicsToDisplay.Length > 0 ? GraphicsToDisplay.Max(graphic => graphic.Length) : 0;
            string[] inputField = new string[cardHeight];

            for (int i = 0; i < cardHeight; i++)
            {
                StringBuilder lineBuilder = new();

                for (int j = 0; j < GraphicsToDisplay.Length; j++)
                {
                    lineBuilder.Append(GraphicsToDisplay[j][i]);
                    if (j < GraphicsToDisplay.Length - 1) lineBuilder.Append(' ');
                }

                inputField[i] = lineBuilder.ToString();
            }

            return inputField;
        }
        private string[] GeneratePlayableCardGraphic(PlayableCard card)
        {
            return CardGraphicUtil.GeneratePlayableCardGraphic(card.Graphic, card.Name, card.CurrentPower, card.Id == _targeter.GetTargetId());
        }
        private string[] GenerateDisplayCardGraphic()
        {
            if(_cardToDisplay != null)
            {
                string[] graphic = GeneratePlayableCardGraphic(_cardToDisplay);

                if (_displayText != null) graphic[graphic.Length / 2] += $" {_displayText}";

                return graphic;
            }

            return [];
        }

        /// <summary>
        /// Generates the end turn button
        /// </summary>
        /// <returns></returns>
        private string[] GenerateEndTurnField(int lineWidth)
        {
            // Add End Button
            List<string> button;
            if (_targeter.GetTargetId() == END_TURN_BUTTON_ID)
            {
                button = ["╔════════╗", "║END TURN║", "╚════════╝"];
            }
            else
            {
                button = ["┌────────┐", "│END TURN│", "└────────┘"];
            }
            return button.Select(x => RenderUtil.CenterString(x, lineWidth)).ToArray();
        }

        public override Guid? HandleKeyPress(UserKeyPress keyPress)
        {
            return _targeter.HandleKeyPress(keyPress);
        }
    }
}
